export const SET_LAYOUT_TYPE = 'SET_LAYOUT_TYPE'
export const SET_THEME = 'SET_THEME'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_TAB = 'SET_TAB'
export const SET_BREADCRUMB = 'SET_BREADCRUMB'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_TABS_ROUTE = 'SET_TABS_ROUTE'
